# Generated by Django 5.0.3 on 2024-03-24 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
